### ISSUE TITLE
Curso Python #07 – Operadores Aritméticos

### ISSUE THREAD

**Issue by josias-almeida** [josias-almeida/josias-almeida#1]
- [ ] Exercício Python #005 – Antecessor e Sucessor

- [ ] Exercício Python #006 – Dobro, Triplo, Raiz Quadrada

- [ ] Exercício Python #007 – Média Aritmética

- [ ] Exercício Python #008 – Conversor de Medidas

- [ ] Exercício Python #009 – Tabuada

- [ ] Exercício Python #010 – Conversor de Moedas

- [ ] Exercício Python #011 – Pintando Parede

- [ ] Exercício Python #012 – Calculando Descontos

- [ ] Exercício Python #013 – Reajuste Salarial

- [ ] Exercício Python #014 – Conversor de Temperaturas

- [ ] Exercício Python #015 – Aluguel de Carros
