### ISSUE TITLE
Curso Python #08 – Utilizando Módulos

### ISSUE THREAD

**Issue by josias-almeida** [josias-almeida/josias-almeida#4]
- [ ] Exercício Python #016 – Quebrando um número

- [ ] Exercício Python #017 – Catetos e Hipotenusa

- [ ] Exercício Python #018 – Seno, Cosseno e Tangente

- [ ] Exercício Python #019 – Sorteando um item na lista

- [ ] Exercício Python #020 – Sorteando uma ordem na lista

- [ ] Exercício Python #021 – Tocando um MP3
