### ISSUE TITLE
Curso Python #09 – Manipulando Texto

### ISSUE THREAD

**Issue by josias-almeida** [josias-almeida/josias-almeida#5]
- [ ] Exercício Python #022 – Analisador de Textos

- [ ] Exercício Python #023 – Separando dígitos de um número

- [ ] Exercício Python #024 – Verificando as primeiras letras de um texto

- [ ] Exercício Python #025 – Procurando uma string dentro de outra

- [ ] Exercício Python #026 – Primeira e última ocorrência de uma string

- [ ] Exercício Python #027 – Primeiro e último nome de uma pessoa
