### ISSUE TITLE
Curso Python #10 – Condições (Parte 1)

### ISSUE THREAD

**Issue by josias-almeida** [josias-almeida/josias-almeida#6]
- [ ] Exercício Python #028 – Jogo da Adivinhação v.1.0

- [ ] Exercício Python #029 – Radar eletrônico

- [ ] Exercício Python #030 – Par ou Ímpar?

- [ ] Exercício Python #031 – Custo da Viagem

- [ ] Exercício Python #032 – Ano Bissexto

- [ ] Exercício Python #033 – Maior e menor valores

- [ ] Exercício Python #034 – Aumentos múltiplos

- [ ] Exercício Python #035 – Analisando Triângulo v1.0
